name: Validate Pull Request
on:
  pull_request:
    branches: [ main ]
jobs:
  check_formatting:
    runs-on: ubuntu-latest
    name: Check Formatting
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            7.0.100
            6.0.300
      - run: |
          dotnet tool restore
          dotnet csharpier . --check

